### ISSUE TITLE
Deprecation of Shopify's `Metafield.valueType`

### ISSUE THREAD

**Issue by joao-conde** [hivesolutions/shopify_api#19]
## Rationale

This API client becomes unusable for the latest Shopify API version. It is business critical that this is compliant with their new API while maintaining retro-compatibility with other API versions.

## Description

The latest version of the Shopify API will deprecate the field `Metafield.valueType` in favor of `Metafield.type`.

### Software development

Change:

- https://github.com/hivesolutions/shopify-api/blob/f7b484c469ae724418baab965c88c6112146d06f/src/shopify/product.py#L97

- https://github.com/hivesolutions/shopify-api/blob/98595b8c7f8814b8b2435447889d74a92aaec4c3/src/shopify/order.py#L118

To accept both `value_type` and `type` as kwargs and set the metafield dictionary with `type = VALUE` thus maintaining retro compatibility.

## Reference

- https://shopify.dev/apps/metafields/migration
- https://community.shopify.com/c/shopify-apis-and-sdks/deprecated-api-calls-metafield-valuetype/td-p/1594073

![image](https://user-images.githubusercontent.com/16060539/209562017-efae2db8-7483-4441-8dc9-1b3bb4b1d4e4.png)

**Comment by joamag** [comment]
@joao-conde go ahead create a fork and make the changes :)

**Comment by joamag** [comment]
@joao-conde also, if there's a URL describing the deprecation (on the Shopify doc side) please add it to the description for future reference

**Comment by joao-conde** [comment]
@joamag  added what I could find, the rest is a company private email which even I dont have access to.

**Comment by joamag** [comment]
found another reference to this topic https://shopify.dev/apps/metafields/migration

**Comment by joamag** [comment]
Releasing 0.6.5 with this fix. Closing this issue.
