### ISSUE TITLE
Missing `_build_admin_url()` error

### ISSUE THREAD

**Issue by NFSS10** [hivesolutions/shopify_api#22]
`shopify-api` isn't working properly since version `0.7.0`:
![imagem](https://user-images.githubusercontent.com/22588915/212545644-170bcba5-9f50-4c65-99b2-7e244e11e135.png)

This issue appears since the change made here: https://github.com/hivesolutions/shopify-api/commit/b5e32149d95c717d88c63465bfe3b879e5c22719

The fix could be revert that change or apply that refactor to the other revelant places, as in here: https://github.com/hivesolutions/shopify-api/blob/825747986353e81b6cb8b2a501226a55a29d8b6a/src/shopify/base.py#L259

**Comment by joamag** [comment]
This issue is fixed by https://github.com/hivesolutions/shopify-api/commit/793253f74a4238558a06c0b95a8f5dff4b127a99

**Comment by joamag** [comment]
Fix released as part of the 0.7.1 version
